version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: container_postgres
    restart: always
    environment:
      POSTGRES_USER: dorado
      POSTGRES_PASSWORD: dorado
      POSTGRES_DB: doradodb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql